static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: proxy
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: loopback
          http_filters:
          - name: envoy.filters.http.router

  - name: listener_1
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: loopback_http
          local_reply_config:
            mappers:
            - filter:
                header_filter:
                  header:
                    name: ":method"
                    exact_match: "GET"
              body_format_override:
                text_format_source:
                  inline_string: |
                    <html>
                      <body>
                        <h1>Welcome to Envoy</h1>
                        <h2>
                          check out the <a href='https://www.envoyproxy.io'>Envoy website</a>
                          and <a href='https://www.envoyproxy.io/docs'>documentation</a>
                        </h2>
                      </body>
                    </html>
                content_type: "text/html; charset=UTF-8"
          route_config:
            name: local_route
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: loopback
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: loopback
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 10001
